name: Package Application with PyInstaller

on:
  release:
    types: [created]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name cleanup-web_windows --windowed --add-data "requirements.txt;." main.py

      - uses: actions/upload-artifact@v4
        with:
          name: cleanup-web_windows
          path: dist/cleanup-web_windows.exe
          retention-days: 1

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-xinerama0

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name cleanup-web_linux --windowed --add-data "requirements.txt:." main.py

      - uses: actions/upload-artifact@v4
        with:
          name: cleanup-web_linux
          path: dist/cleanup-web_linux
          retention-days: 1

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --name cleanup-web_macos --windowed --add-data "requirements.txt:." main.py

      - uses: actions/upload-artifact@v4
        with:
          name: cleanup-web_macos
          path: dist/cleanup-web_macos
          retention-days: 1
